<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Are you sure you want to delete this item?' => 'Weet u zeker dat u dit item wilt verwijderen?',
  'Delete' => 'Verwijderen',
  'Displaying {start}-{end} of {count} result(s).' => 'Resultaten {start}-{end} van {count}',
  'Either "name" or "value" must be specified for CDataColumn.' => '',
  'Home' => '',
  'No results found.' => 'Geen resultaten gevonden',
  'Not set' => '',
  'Please specify the "attributes" property.' => '',
  'Please specify the "data" property.' => '',
  'Sort by: ' => 'Sorteer op',
  'The "dataProvider" property cannot be empty.' => '',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => '',
  'The button type "{type}" is not supported.' => '',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => '',
  'The property "itemView" cannot be empty.' => '',
  'Total {count} result(s).' => 'Totaal {count} resultaten.',
  'Update' => 'Bewerken',
  'View' => 'Bekijken',
  '{class} must specify "model" and "attribute" or "name" property values.' => '',
);
